name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Login to DockerHub
      uses: docker/login-action@v1.13.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Website Docker images
      id: docker_build_push_website
      uses: docker/build-push-action@v2.9.0
      with:
        file: ./Dockerfile
        tags: wankenobi/abq-web:1.0.1
        push: true
    
