name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Website Docker images
      id: docker_build_push_website
      uses: docker/build-push-action@v2.2.1
      with:
        file: ./alphabloQ.github.io/Dockerfile
        tags: wankenobi/abq-web:1.0.1
        push: true
